%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjusted for your simulated pinhole camera
#--------------------------------------------------------------------------------------------

Camera.type: "PinHole"
Camera.width: 640
Camera.height: 480

Camera.fx: 521.93325
Camera.fy: 521.93327
Camera.cx: 320.0
Camera.cy: 240.0

# No distortion
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

# Camera frames per second (adjust if needed)
Camera.fps: 30.0

# Color order (simulation usually outputs RGB)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor.nFeatures: 1200
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer
#--------------------------------------------------------------------------------------------

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
